language: php
php:
  - '7.0'
  - nightly

install:
  - composer install --dev

script:
  - phpunit --coverage-clover cover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=1888c139c4141faf514667ec9e2da4e496f01ef23d5c47fbb3904ac65189681b vendor/bin/test-reporter --coverage-report=cover.xml